server {
    listen 80;
    server_name localhost;

    # Directorio de los archivos estáticos (donde copiaremos el build de Vite)
    root /usr/share/nginx/html;
    index index.html;

    # Configuración para soportar SPA (Single Page Application)
    # Redirige cualquier ruta desconocida a index.html para que react-router tome el control
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Caché estática para mejorar el rendimiento
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|json|webmanifest)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    # Configuración de compresión Gzip para archivos más rápidos
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}
